name: testing how workflow works
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: setup...
        run: make setup
      - name: testing
        run: make test
      - name: check linter
        run: make lint
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.b79ba244-ce89-4fd9-907b-80243bb2a526}}      
        with:
          args: --severity-threshold=high  