name: testing how workflow works
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: setup...
        run: make setup
      - name: start
        run: make start  
      - name: testing
        run: make test
      - name: check linter
        run: make lint
   